//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.SAFE
{
    public partial class LEO_OfficerBadges
    {
        public LEO_OfficerBadges()
        {
            this.Safe_CitationPoliceOfficers = new HashSet<Safe_CitationPoliceOfficers>();
            this.Safe_HearingPoliceOfficers = new HashSet<Safe_HearingPoliceOfficers>();
        }
    
        public short OfficerBadgeID { get; set; }
        public string SerialNumber { get; set; }
        public byte PoliceDepartmentID { get; set; }
        public int PersonID { get; set; }
        public System.DateTime WhenBecomesActive { get; set; }
        public System.DateTime WhenExpires { get; set; }
        public short C_DataChanges_RowID { get; set; }
        public string OfficerRankTitleDescription { get; set; }
    
        public virtual ICollection<Safe_CitationPoliceOfficers> Safe_CitationPoliceOfficers { get; set; }
        public virtual ICollection<Safe_HearingPoliceOfficers> Safe_HearingPoliceOfficers { get; set; }
        public virtual Person_FullName_LastFirst Person_FullName { get; set; }
    }
    
}
