//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.SAFE
{
    public partial class Person_PersonDivisionXref
    {
        public Person_PersonDivisionXref()
        {
            this.Person_Badges = new HashSet<Person_Badges>();
        }
    
        public int PersonDivisionXrefID { get; set; }
        public int PersonID { get; set; }
        public int DivisionID { get; set; }
        public System.DateTime WhenAccepted { get; set; }
        public System.DateTime WhenBegins { get; set; }
        public System.DateTime WhenEnds { get; set; }
    
        public virtual Person_FullName Person_FullName { get; set; }
        public virtual Division_Divisions Division_Divisions { get; set; }
        public virtual ICollection<Person_Badges> Person_Badges { get; set; }
        public virtual Person_FullName_LastFirst Person_FullName_LastFirst { get; set; }
    }
    
}
