//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.SAFE
{
    public partial class Safe_Hearings
    {
        public Safe_Hearings()
        {
            this.Safe_HearingPoliceOfficers = new HashSet<Safe_HearingPoliceOfficers>();
        }
    
        public int SafeHearingID { get; set; }
        public int SafeCitationID { get; set; }
        public int SafeOfficerID_Hearing { get; set; }
        public Nullable<System.DateTime> WhenHearingHeld { get; set; }
        public Nullable<System.DateTime> WhenAppealToBeHeld { get; set; }
        public Nullable<System.DateTime> WhenTrainingHeld { get; set; }
        public Nullable<System.DateTime> WhenCompleted { get; set; }
        public string HearingNotes { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
        public string C_Legacy_TableName { get; set; }
        public int C_DataChanges_RowID { get; set; }
        public string Superintendent { get; set; }
    
        public virtual ICollection<Safe_HearingPoliceOfficers> Safe_HearingPoliceOfficers { get; set; }
        public virtual Safe_Officers Safe_Officers { get; set; }
    }
    
}
