//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.SAFE
{
    public partial class Safe_Citations
    {
        public Safe_Citations()
        {
            this.Safe_CitationPoliceOfficers = new HashSet<Safe_CitationPoliceOfficers>();
            this.Safe_CitationViolations = new HashSet<Safe_CitationViolations>();
            this.Safe_Hearings = new HashSet<Safe_Hearings>();
        }
    
        public int SafeCitationID { get; set; }
        public string CitationNumber { get; set; }
        public int PersonDivisionXrefID { get; set; }
        public Nullable<int> BadgeID { get; set; }
        public Nullable<int> VehicleMakeID { get; set; }
        public Nullable<int> VehicleBodyID { get; set; }
        public string CountryCode_LicensePlate { get; set; }
        public string CountrySubdivisionCode_LicensePlate { get; set; }
        public string LicensePlate { get; set; }
        public bool BadgeUnknown { get; set; }
        public bool BadgeDisplayed { get; set; }
        public bool DriverIcon { get; set; }
        public bool LicenseValid { get; set; }
        public bool DriverTrainingRequired { get; set; }
        public bool SecurityTrainingRequired { get; set; }
        public bool IsDeleted { get; set; }
        public string ViolationLocation { get; set; }
        public string Cancelled { get; set; }
        public string FollowUp { get; set; }
        public System.DateTime WhenCreated { get; set; }
        public Nullable<System.DateTime> WhenDue { get; set; }
        public Nullable<System.DateTime> WhenResolved { get; set; }
        public int C_DataChanges_RowID { get; set; }
        public string DriversLicenseNumber { get; set; }
        public string VehicleIdentification { get; set; }
        public string Conditions { get; set; }
        public string Superintendent { get; set; }
    
        public virtual ICollection<Safe_CitationPoliceOfficers> Safe_CitationPoliceOfficers { get; set; }
        public virtual Safe_VehicleBodyTypes Safe_VehicleBodyTypes { get; set; }
        public virtual Safe_VehicleMakes Safe_VehicleMakes { get; set; }
        public virtual ICollection<Safe_CitationViolations> Safe_CitationViolations { get; set; }
        public virtual ICollection<Safe_Hearings> Safe_Hearings { get; set; }
        public virtual Person_PersonDivisionXref Person_PersonDivisionXref { get; set; }
        public virtual Person_Badges Person_Badges { get; set; }
    }
    
}
