//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.SAFE
{
    public partial class Safe_Officers
    {
        public int SafeOfficerID { get; set; }
        public int SafeDivisionID { get; set; }
        public string OfficerName { get; set; }
        public string OfficerBadgeNumber { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
        public string C_Legacy_TableName { get; set; }
        public int C_DataChanges_RowID { get; set; }
    }
    
}
