//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.SAFE
{
    public partial class Safe_Violations
    {
        public int ViolationID { get; set; }
        public string ViolationNumber { get; set; }
        public string ViolationDescription { get; set; }
        public short ViolationTypeID { get; set; }
        public byte ViolationPoints { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
        public string C_Legacy_TableName { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual Safe_ViolationTypes Safe_ViolationTypes { get; set; }
    }
    
}
