//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.SAFE
{
    public partial class Safe_HearingPoliceOfficers
    {
        public int SafeHearingID { get; set; }
        public short OfficerBadgeID { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual LEO_OfficerBadges LEO_OfficerBadges { get; set; }
    }
    
}
