//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Audit_AuditDocuments
    {
        public int AuditDocumentID { get; set; }
        public int DivisionID { get; set; }
        public int AuditSpecificationID { get; set; }
        public string AuditDocumentTypeCode { get; set; }
        public byte[] DocumentImage { get; set; }
        public System.DateTime WhenCreated { get; set; }
        public int C_DataChanges_RowID { get; set; }
        public string DocumentFilename { get; set; }
    }
    
}
