//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Audit_AuditGroups
    {
        public int AuditGroupID { get; set; }
        public string FacilityCode { get; set; }
        public string GroupName { get; set; }
        public System.DateTime AuditDate { get; set; }
        public int C_DataChanges_RowID { get; set; }
    }
    
}
