//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class IWS_Person_Person
    {
        public IWS_Person_Person()
        {
            this.Person_PersonBadgeXref = new HashSet<IWS_Person_PersonBadgeXref>();
            this.Person_Persons = new HashSet<Lookups_Person_Persons>();
        }
    
        public System.Guid PersonID_IWS { get; set; }
        public int EMP_ID { get; set; }
        public string SSN { get; set; }
        public string Source { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
        public Nullable<int> C_Legacy_PersonID_IWS_Integer { get; set; }
    
        public virtual ICollection<IWS_Person_PersonBadgeXref> Person_PersonBadgeXref { get; set; }
        public virtual ICollection<Lookups_Person_Persons> Person_Persons { get; set; }
    }
    
}
