//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class IWS_Person_Demographics
    {
        public int C_Legacy_EMP_ID { get; set; }
        public string Source { get; set; }
        public string SSN { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string Suffix { get; set; }
        public string AddressLine { get; set; }
        public string City { get; set; }
        public string CountrySubdivisionCode { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
        public string HomePhone { get; set; }
        public string WorkPhone { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<int> HT_FT { get; set; }
        public Nullable<int> HT_IN { get; set; }
        public Nullable<int> HeightInInches { get; set; }
        public Nullable<int> WeightInPounds { get; set; }
        public string Sex { get; set; }
        public string EyeColorCode { get; set; }
        public string HairColorCode { get; set; }
        public string EthnicityCode { get; set; }
        public Nullable<System.DateTime> PIC_DT { get; set; }
        public byte[] Picture { get; set; }
        public string Notes { get; set; }
        public string IsHotNote { get; set; }
        public string PIN { get; set; }
        public string MiscInfo { get; set; }
        public string Fingerprint { get; set; }
        public Nullable<System.DateTime> PrintsDate { get; set; }
        public string DoNotBadge { get; set; }
        public string FingerprintExempt { get; set; }
        public string UserID { get; set; }
        public string DOJFlag { get; set; }
        public string HiddenFlag { get; set; }
        public string LastUserDateAccessed { get; set; }
        public string Masked_SSN { get; set; }
        public Nullable<System.DateTime> DojPrinted { get; set; }
        public string DojPrintedFlag { get; set; }
        public Nullable<System.DateTime> LastDateAccessed { get; set; }
        public string LastUserAccessed { get; set; }
        public Nullable<int> DL_DocumentTypeNumber { get; set; }
        public string DL_IdentificationNumber { get; set; }
        public string DL_IssuingStateCode { get; set; }
        public Nullable<System.DateTime> DL_ExpirationDate { get; set; }
        public Nullable<int> OtherID_DocumentTypeNumber { get; set; }
        public string OtherID_IdentificationNumber { get; set; }
        public string OtherID_DocumentDescription { get; set; }
        public Nullable<System.DateTime> OtherID_ExpirationDate { get; set; }
        public string Alien { get; set; }
        public Nullable<int> Alien_DocumentTypeNumber { get; set; }
        public string Alien_IdentificationNumber { get; set; }
        public string Alien_DocumentDescription { get; set; }
        public Nullable<System.DateTime> Alien_ExpirationDate { get; set; }
        public string Alien_IssuingCountryCode { get; set; }
        public string Visa { get; set; }
        public Nullable<int> Visa_DocumentTypeNumber { get; set; }
        public string Visa_IdentificationNumber { get; set; }
        public string Visa_DocumentDescription { get; set; }
        public Nullable<System.DateTime> Visa_ExpirationDate { get; set; }
        public string Visa_IssuingCountryCode { get; set; }
        public Nullable<int> Passport_DocumentTypeNumber { get; set; }
        public string Passport_IdentificationNumber { get; set; }
        public Nullable<System.DateTime> Passport_ExpirationDate { get; set; }
        public string Passport_IssuingCountryCode { get; set; }
        public string CitizenshipCountry { get; set; }
        public string PlaceBirthCode { get; set; }
        public string UsCitizen { get; set; }
        public string VerificationType { get; set; }
        public string Assessment { get; set; }
        public string SboVerified { get; set; }
        public string InsExempt { get; set; }
        public Nullable<int> I94_DocumentTypeNumber { get; set; }
        public string I94_IdentificationNumber { get; set; }
        public Nullable<System.DateTime> I94_ExpirationDate { get; set; }
        public Nullable<int> CertNat_DocumentTypeNumber { get; set; }
        public string CertNat_IdentificationNumber { get; set; }
        public Nullable<int> DS1350_DocumentTypeNumber { get; set; }
        public string DS1350_IdentificationNumber { get; set; }
        public Nullable<int> BirthCert_DocumentTypeNumber { get; set; }
        public string FedEmp { get; set; }
        public string FedID { get; set; }
        public Nullable<int> ListBDocumentTypeNumber { get; set; }
        public Nullable<int> ListCDocumentTypeNumber { get; set; }
        public string AliasLastName { get; set; }
        public string AliasFirstName { get; set; }
        public string AliasMiddleName { get; set; }
        public string AliasSuffix { get; set; }
        public string Email { get; set; }
        public string HotNotes { get; set; }
        public Nullable<int> DocumentTypeNumber { get; set; }
        public string DocumentIdentificationNumber { get; set; }
        public string IssuingStateCode { get; set; }
        public string DocumentDescription { get; set; }
        public Nullable<System.DateTime> DocumentExpirationDate { get; set; }
        public Nullable<int> status { get; set; }
        public string employee { get; set; }
        public string Initials { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public Nullable<System.DateTime> PrintExpiryDate { get; set; }
        public Nullable<System.DateTime> ContractExpiryDate { get; set; }
        public string StateCode_Citizenship { get; set; }
        public string StateCode_Birth { get; set; }
        public string Validated { get; set; }
        public Nullable<System.DateTime> DateOfValidation { get; set; }
        public string STAStatus { get; set; }
        public string FPClassification { get; set; }
        public string Alias1 { get; set; }
        public Nullable<int> VerificationDocumentType { get; set; }
        public string FingerprintCode { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
    
        public virtual Miscellaneous_CountrySubdivisions Miscellaneous_CountrySubdivisions { get; set; }
    }
    
}
