//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class IWS_Person_PersonBadgeXref
    {
        public System.Guid PersonID_IWS { get; set; }
        public long BadgeID_IWS { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
    
        public virtual IWS_Person_Person Person_Person { get; set; }
        public virtual IWS_Badge_Badge Badge_Badge { get; set; }
    }
    
}
