//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class LEO_OfficerRanksAndTitles
    {
        public byte OfficerRankAndTitleID { get; set; }
        public byte OfficerTypeID { get; set; }
        public string OfficerRankTitleDescription { get; set; }
        public string OfficerRankTitleAbbreviation { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public byte C_DataChanges_RowID { get; set; }
    
        public virtual LEO_OfficerTypes LEO_OfficerTypes { get; set; }
    }
    
}
