//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class LEO_PoliceDepartments
    {
        public byte PoliceDepartmentID { get; set; }
        public string PoliceDepartmentDescription { get; set; }
        public string PoliceDepartmentAbbreviation { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public byte C_DataChanges_RowID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string CountryCode { get; set; }
        public string CountrySubdivisionCode { get; set; }
        public string PostalCode { get; set; }
    
        public virtual Miscellaneous_Countries Miscellaneous_Countries { get; set; }
        public virtual Miscellaneous_CountrySubdivisions Miscellaneous_CountrySubdivisions { get; set; }
    }
    
}
