//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class LEO_OfficerBadges
    {
        public short OfficerBadgeID { get; set; }
        public string SerialNumber { get; set; }
        public byte PoliceDepartmentID { get; set; }
        public int PersonID { get; set; }
        public System.DateTime WhenBecomesActive { get; set; }
        public System.DateTime WhenExpires { get; set; }
        public short C_DataChanges_RowID { get; set; }
    
        public virtual Lookups_Person_Persons Person_Persons { get; set; }
    }
    
}
