//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class LEO_Officers
    {
        public short OfficerBadgeID { get; set; }
        public string BadgeStatusCode { get; set; }
        public int PersonID { get; set; }
        public string SerialNumber { get; set; }
        public string NAME { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string NameSuffixCode { get; set; }
        public byte OfficerRankAndTitleID { get; set; }
        public string OfficerRankTitleAbbreviation { get; set; }
        public string OfficerRankTitleDescription { get; set; }
        public byte OfficerTypeID { get; set; }
        public string OfficerTypeDescription { get; set; }
        public string OfficerTypeAbbreviation { get; set; }
        public byte PoliceDepartmentID { get; set; }
        public string PoliceDepartmentDescription { get; set; }
        public string PoliceDepartmentAbbreviation { get; set; }
        public System.DateTime LBSP_WBA { get; set; }
        public System.DateTime WhenBecomesActive { get; set; }
        public System.DateTime LBSP_WE { get; set; }
        public System.DateTime WhenExpires { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string Person_FullName { get; set; }
    }
    
}
