//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Person_BadgeStatuses
    {
        public string BadgeStatusCode { get; set; }
        public string BadgeStatusDescription { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
        public string C_Legacy_TableName { get; set; }
        public int C_DataChanges_RowID { get; set; }
        public string StatusType { get; set; }
        public Nullable<bool> Police_Specific { get; set; }
        public Nullable<bool> BO_Specific { get; set; }
        public Nullable<bool> VAAU_Specific { get; set; }
    }
    
}
