//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_TaskType
    {
        public short TaskTypeID { get; set; }
        public string TaskDescription { get; set; }
        public string TaskNotes { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public string ProcedureName { get; set; }
        public short C_DataChanges_RowID { get; set; }
    }
    
}
