//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Facility_BadgeColors
    {
        public Lookups_Facility_BadgeColors()
        {
            this.Division_AgreementBadgeColors = new HashSet<Lookups_Division_AgreementBadgeColors>();
            this.Division_AgreementBadgeIcons = new HashSet<Lookups_Division_AgreementBadgeIcons>();
            this.Person_Badges = new HashSet<Lookups_Person_Badges>();
            this.Company_Companies = new HashSet<Lookups_Company_Companies>();
        }
    
        public short BadgeColorID { get; set; }
        public string FacilityCode { get; set; }
        public string BadgeColor { get; set; }
        public byte Level { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public short C_DataChanges_RowID { get; set; }
        public string BadgeType { get; set; }
    
        public virtual ICollection<Lookups_Division_AgreementBadgeColors> Division_AgreementBadgeColors { get; set; }
        public virtual ICollection<Lookups_Division_AgreementBadgeIcons> Division_AgreementBadgeIcons { get; set; }
        public virtual ICollection<Lookups_Person_Badges> Person_Badges { get; set; }
        public virtual ICollection<Lookups_Company_Companies> Company_Companies { get; set; }
    }
    
}
