//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Colors
    {
        public byte ColorID { get; set; }
        public string ColorName { get; set; }
        public string HtmlColorCode { get; set; }
        public byte RedComponent { get; set; }
        public byte GreenComponent { get; set; }
        public byte BlueComponent { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public byte C_DataChanges_RowID { get; set; }
    }
    
}
