//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Division_ContactTypes
    {
        public short ContactTypeID { get; set; }
        public string ContactTypeDescription { get; set; }
        public string ContactTypeAbbreviation { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public short C_DataChanges_RowID { get; set; }
    }
    
}
