//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Common_Requirement_ContentTypes_Extensions
    {
        public string ContentTypeCode { get; set; }
        public string FileExtention { get; set; }
        public int C_DataChanges_RowID { get; set; }
    }
    
}
