//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Person_FelonyQuestions
    {
        public Lookups_Person_FelonyQuestions()
        {
            this.Person_FelonyAnswers = new HashSet<Lookups_Person_FelonyAnswers>();
        }
    
        public int FelonyQuestionID { get; set; }
        public string FelonyQuestionAbbreviation { get; set; }
        public string FelonyQuestionDescription { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual ICollection<Lookups_Person_FelonyAnswers> Person_FelonyAnswers { get; set; }
    }
    
}
