//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Common_Entities
    {
        public Lookups_Common_Entities()
        {
            this.Common_Requirement_Documents = new HashSet<Lookups_Common_Requirement_Documents>();
        }
    
        public int EntityID { get; set; }
        public Nullable<int> AccessRequestID { get; set; }
        public Nullable<int> AgreementID { get; set; }
        public Nullable<int> AuditSpecificationID { get; set; }
        public Nullable<int> BadgeID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> DivisionID { get; set; }
        public Nullable<int> DivisionRequestID { get; set; }
        public Nullable<int> FormDataID { get; set; }
        public Nullable<int> IconRequestID { get; set; }
        public Nullable<int> PersonDivisionXrefID { get; set; }
        public Nullable<int> SafeHearingID { get; set; }
        public string EntityTypeCode { get; set; }
        public int C_DataChanges_RowID { get; set; }
        public Nullable<int> ShadowAgreementID { get; set; }
        public Nullable<int> ShadowBadgeID { get; set; }
        public Nullable<int> ShadowCompanyID { get; set; }
        public Nullable<int> ShadowDivisionID { get; set; }
        public Nullable<int> ShadowPersonDivisionXrefID { get; set; }
    
        public virtual Lookups_Division_Agreements Division_Agreements { get; set; }
        public virtual Person_PersonDivisionXref Person_PersonDivisionXref { get; set; }
        public virtual Lookups_Person_Badges Person_Badges { get; set; }
        public virtual Lookups_Common_EntityTypes Common_EntityTypes { get; set; }
        public virtual Lookups_Division_Divisions Division_Divisions { get; set; }
        public virtual Lookups_Company_Companies Company_Companies { get; set; }
        public virtual ICollection<Lookups_Common_Requirement_Documents> Common_Requirement_Documents { get; set; }
        public virtual Lookups_Audit_AuditSpecifications Audit_AuditSpecifications { get; set; }
    }
    
}
