//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Division_Agreements
    {
        public Lookups_Division_Agreements()
        {
            this.Division_Agreements1 = new HashSet<Lookups_Division_Agreements>();
            this.Division_AgreementBadgeColors = new HashSet<Lookups_Division_AgreementBadgeColors>();
            this.Division_AgreementBadgeIcons = new HashSet<Lookups_Division_AgreementBadgeIcons>();
            this.Common_Entities = new HashSet<Lookups_Common_Entities>();
            this.Division_AgreementAccessDefaults = new HashSet<Lookups_Division_AgreementAccessDefaults>();
            this.Division_AgreementJobRoles = new HashSet<Lookups_Division_AgreementJobRoles>();
            this.Division_AgreementLocations = new HashSet<Lookups_Division_AgreementLocations>();
        }
    
        public int AgreementID { get; set; }
        public int DivisionID { get; set; }
        public string AgreementNumber { get; set; }
        public short AgreementTypeID { get; set; }
        public string DirectAuthorityNumber { get; set; }
        public string OtherAgreementType { get; set; }
        public System.DateTime WhenAgreementBegins { get; set; }
        public System.DateTime WhenAgreementEnds { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
        public string C_Legacy_TableName { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual ICollection<Lookups_Division_Agreements> Division_Agreements1 { get; set; }
        public virtual Lookups_Division_Agreements Division_Agreements2 { get; set; }
        public virtual ICollection<Lookups_Division_AgreementBadgeColors> Division_AgreementBadgeColors { get; set; }
        public virtual ICollection<Lookups_Division_AgreementBadgeIcons> Division_AgreementBadgeIcons { get; set; }
        public virtual ICollection<Lookups_Common_Entities> Common_Entities { get; set; }
        public virtual ICollection<Lookups_Division_AgreementAccessDefaults> Division_AgreementAccessDefaults { get; set; }
        public virtual Lookups_Division_Divisions Division_Divisions { get; set; }
        public virtual ICollection<Lookups_Division_AgreementJobRoles> Division_AgreementJobRoles { get; set; }
        public virtual ICollection<Lookups_Division_AgreementLocations> Division_AgreementLocations { get; set; }
    }
    
}
