//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Common_Requirement_Requirements
    {
        public Lookups_Common_Requirement_Requirements()
        {
            this.Common_Requirement_DocumentsRequired = new HashSet<Lookups_Common_Requirement_DocumentsRequired>();
        }
    
        public string RequirementCode { get; set; }
        public string RequirementDescription { get; set; }
        public string ActionRequired { get; set; }
        public bool IsDocument { get; set; }
        public Nullable<int> TrainingProgramID { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual Lookups_Common_EntityTypes Common_EntityTypes { get; set; }
        public virtual ICollection<Lookups_Common_Requirement_DocumentsRequired> Common_Requirement_DocumentsRequired { get; set; }
        public virtual Lookups_Facility_Departments Facility_Departments { get; set; }
    }
    
}
