//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Person_JobRoles
    {
        public Lookups_Person_JobRoles()
        {
            this.Division_AgreementAccessDefaults = new HashSet<Lookups_Division_AgreementAccessDefaults>();
            this.Division_AgreementBadgeColors = new HashSet<Lookups_Division_AgreementBadgeColors>();
            this.Division_AgreementJobRoles = new HashSet<Lookups_Division_AgreementJobRoles>();
            this.Person_PersonDivisionJobRoleXref = new HashSet<Lookups_Person_PersonDivisionJobRoleXref>();
        }
    
        public short JobRoleID { get; set; }
        public string JobRoleDescription { get; set; }
        public string JobRoleAbbreviation { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public short C_DataChanges_RowID { get; set; }
    
        public virtual ICollection<Lookups_Division_AgreementAccessDefaults> Division_AgreementAccessDefaults { get; set; }
        public virtual ICollection<Lookups_Division_AgreementBadgeColors> Division_AgreementBadgeColors { get; set; }
        public virtual ICollection<Lookups_Division_AgreementJobRoles> Division_AgreementJobRoles { get; set; }
        public virtual ICollection<Lookups_Person_PersonDivisionJobRoleXref> Person_PersonDivisionJobRoleXref { get; set; }
    }
    
}
