//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Division_AgreementJobRoles
    {
        public int AgreementID { get; set; }
        public short JobRoleID { get; set; }
        public bool IsActive { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual Lookups_Division_Agreements Division_Agreements { get; set; }
        public virtual Lookups_Person_JobRoles Person_JobRoles { get; set; }
    }
    
}
