//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Access_Doors
    {
        public int DoorID { get; set; }
        public string FacilityCode { get; set; }
        public string DoorName { get; set; }
        public int SourceDoorPKID { get; set; }
        public int AreaID { get; set; }
        public Nullable<short> DepartmentID_Authorizer { get; set; }
        public Nullable<int> TSAMaximumBadgeCount { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual Lookups_Access_Areas Access_Areas { get; set; }
        public virtual Lookups_Facility_Departments Facility_Departments { get; set; }
    }
    
}
