//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_TaskParam
    {
        public int TaskParamID { get; set; }
        public int TaskID { get; set; }
        public string ParamName { get; set; }
        public string ValueType { get; set; }
        public string Value { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual Lookups_Task Task { get; set; }
    }
    
}
