//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Person_TrainingSites
    {
        public Lookups_Person_TrainingSites()
        {
            this.Person_Trainers = new HashSet<Lookups_Person_Trainers>();
        }
    
        public short TrainingSiteID { get; set; }
        public string TrainingSiteDescription { get; set; }
        public string TrainingSiteAbbreviation { get; set; }
        public string FacilityCode { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
        public string C_Legacy_TableName { get; set; }
        public short C_DataChanges_RowID { get; set; }
    
        public virtual ICollection<Lookups_Person_Trainers> Person_Trainers { get; set; }
    }
    
}
