//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Security_Users
    {
        public int UserID { get; set; }
        public byte[] ActiveDirectoryUserSID { get; set; }
        public string LoginName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> PasswordExpiresEndOf { get; set; }
        public bool IsActive { get; set; }
        public string FacilityCode { get; set; }
        public Nullable<int> PersonID { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual Lookups_Person_PersonBiographics Person_PersonBiographics { get; set; }
        public virtual Lookups_Person_FullName Person_FullName { get; set; }
    }
    
}
