//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Person_Aliases
    {
        public int PersonAliasID { get; set; }
        public int PersonID { get; set; }
        public string NamePrefixCode { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string NameSuffixCode { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual Lookups_NamePrefixes Miscellaneous_NamePrefixes { get; set; }
        public virtual Lookups_NameSuffixes Miscellaneous_NameSuffixes { get; set; }
        public virtual Lookups_Person_PersonBiographics Person_PersonBiographics { get; set; }
    }
    
}
