//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_BackgroundCheck_PersonDivisionChecks
    {
        public int PersonDivisionCheckID { get; set; }
        public int PersonDivisionXrefID { get; set; }
        public System.DateTime WhenFingerprintTaken { get; set; }
        public Nullable<short> WebMessageID { get; set; }
        public Nullable<System.DateTime> WhenMessageReceived { get; set; }
        public string ResultCode { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
        public string C_Legacy_TableName { get; set; }
        public int C_DataChanges_RowID { get; set; }
        public string Comment { get; set; }
        public bool BadgeIsDenied { get; set; }
        public Nullable<System.DateTime> EffectiveExpirationDate { get; set; }
        public bool IsCopy { get; set; }
    }
    
}
