//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Person_NoteTypes
    {
        public Lookups_Person_NoteTypes()
        {
            this.Person_Notes = new HashSet<Lookups_Person_Notes>();
        }
    
        public string NoteTypeCode { get; set; }
        public string NoteTypeDescription { get; set; }
        public System.DateTime WhenBecomesActive { get; set; }
        public System.DateTime WhenExpires { get; set; }
        public bool IsActive { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual ICollection<Lookups_Person_Notes> Person_Notes { get; set; }
    }
    
}
