//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Access_Areas
    {
        public Lookups_Access_Areas()
        {
            this.Access_CategoryAreaMapping = new HashSet<Lookups_Access_CategoryAreaMapping>();
            this.Access_Doors = new HashSet<Lookups_Access_Doors>();
        }
    
        public int AreaID { get; set; }
        public string FacilityCode { get; set; }
        public string AreaName { get; set; }
        public int SourceAreaPKID { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual ICollection<Lookups_Access_CategoryAreaMapping> Access_CategoryAreaMapping { get; set; }
        public virtual ICollection<Lookups_Access_Doors> Access_Doors { get; set; }
    }
    
}
