//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Person_AuthorizedSigners
    {
        public int DivisionID { get; set; }
        public int PersonID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string PersonTypeStatusCode { get; set; }
        public string SignerCode { get; set; }
        public System.DateTime WhenTrained { get; set; }
        public System.DateTime WhenExpires { get; set; }
        public byte[] SignatureImage { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
        public string C_Legacy_TableName { get; set; }
        public int C_DataChanges_RowID { get; set; }
        public Nullable<System.DateTime> SignatureDate { get; set; }
        public string TrainingType { get; set; }
        public string Instructor { get; set; }
    
        public virtual Lookups_Division_Divisions Division_Divisions { get; set; }
        public virtual Lookups_Person_PersonBiographics Person_PersonBiographics { get; set; }
        public virtual Lookups_Security_Users Security_Users { get; set; }
        public virtual Lookups_Person_FullName Person_FullName { get; set; }
        public virtual Lookups_Person_PersonTypeStatuses Person_PersonTypeStatuses { get; set; }
    }
    
}
