//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Company_Companies
    {
        public Lookups_Company_Companies()
        {
            this.Common_Entities = new HashSet<Lookups_Common_Entities>();
            this.Division_Divisions = new HashSet<Lookups_Division_Divisions>();
            this.Division_Contacts = new HashSet<Lookups_Division_Contacts>();
            this.Person_Trainers = new HashSet<Lookups_Person_Trainers>();
        }
    
        public int CompanyID { get; set; }
        public string CompanyCode { get; set; }
        public string CorporationName { get; set; }
        public string DBAName { get; set; }
        public string BadgeName { get; set; }
        public bool InsuranceRequired { get; set; }
        public bool BTRCRequired { get; set; }
        public Nullable<bool> FingerprintRequired { get; set; }
        public Nullable<bool> BackgroundCheckRequired { get; set; }
        public short BadgeColorID_HighestLevel { get; set; }
        public string ProviderNumber { get; set; }
        public System.DateTime WhenLastUpdated { get; set; }
        public int StaffID_LastUpdated { get; set; }
        public string RAMSAgreementNumber { get; set; }
        public Nullable<System.DateTime> RAMSExpirationDate { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
        public string C_Legacy_TableName { get; set; }
        public Nullable<int> C_Legacy_PrimaryKeyValue { get; set; }
        public int C_DataChanges_RowID { get; set; }
        public Nullable<int> StaffID_BadgeCoordinator { get; set; }
    
        public virtual ICollection<Lookups_Common_Entities> Common_Entities { get; set; }
        public virtual Lookups_Facility_BadgeColors Facility_BadgeColors { get; set; }
        public virtual Lookups_Facility_Staff Facility_Staff { get; set; }
        public virtual Lookups_Facility_Staff Facility_Staff1 { get; set; }
        public virtual ICollection<Lookups_Division_Divisions> Division_Divisions { get; set; }
        public virtual ICollection<Lookups_Division_Contacts> Division_Contacts { get; set; }
        public virtual ICollection<Lookups_Person_Trainers> Person_Trainers { get; set; }
    }
    
}
