//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Audit_AuditSpecifications
    {
        public Lookups_Audit_AuditSpecifications()
        {
            this.Common_Entities = new HashSet<Lookups_Common_Entities>();
        }
    
        public int AuditSpecificationID { get; set; }
        public int AuditGroupID { get; set; }
        public string AuditName { get; set; }
        public string AuditTypeCode { get; set; }
        public string AuditCategoryCode { get; set; }
        public string AuditStatusCode { get; set; }
        public int StaffID_Responsible { get; set; }
        public int BadgesToAudit_TotalNumber { get; set; }
        public byte BadgesToAudit_PercentInDivision { get; set; }
        public Nullable<int> DivisionBadgeMinimum { get; set; }
        public Nullable<int> DivisionBadgeMaximum { get; set; }
        public Nullable<System.DateTime> DivisionAuditDateThreshold { get; set; }
        public int C_DataChanges_RowID { get; set; }
        public Nullable<int> TotalDivisionBadges { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
    
        public virtual ICollection<Lookups_Common_Entities> Common_Entities { get; set; }
        public virtual Lookups_Facility_Staff Facility_Staff { get; set; }
    }
    
}
