//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Person_PersonBiographics
    {
        public Lookups_Person_PersonBiographics()
        {
            this.Person_FelonyAnswers = new HashSet<Lookups_Person_FelonyAnswers>();
            this.Person_Aliases = new HashSet<Lookups_Person_Aliases>();
            this.Security_Users = new HashSet<Lookups_Security_Users>();
            this.Person_Trainers = new HashSet<Lookups_Person_Trainers>();
        }
    
        public int PersonID { get; set; }
        public string NamePrefixCode { get; set; }
        public string FirstName { get; set; }
        public string FirstName_Sound { get; set; }
        public string MiddleName { get; set; }
        public string MiddleName_Sound { get; set; }
        public string LastName { get; set; }
        public string LastName_Sound { get; set; }
        public string NameSuffixCode { get; set; }
        public string Address { get; set; }
        public string ApartmentNumber { get; set; }
        public string City { get; set; }
        public string CountrySubdivisionCode { get; set; }
        public string PostalCode { get; set; }
        public string CountryCode { get; set; }
        public string SocialSecurityNumber { get; set; }
        public string HomePhoneNumber { get; set; }
        public string WorkPhoneNumber { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<byte> HeightInInches { get; set; }
        public Nullable<short> WeightInPounds { get; set; }
        public string EyeColorCode { get; set; }
        public string HairColorCode { get; set; }
        public string RaceCode { get; set; }
        public string SexCode { get; set; }
        public string CountryCode_Birth { get; set; }
        public string CountrySubdivisionCode_Birth { get; set; }
        public string EmailAddress_Primary { get; set; }
        public string EmailAddress_Alternate { get; set; }
        public bool IsSubmitted { get; set; }
        public string FormCode { get; set; }
        public Nullable<System.Guid> FormID { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
        public string C_Legacy_TableName { get; set; }
        public int C_DataChanges_RowID { get; set; }
        public string CountryCode_Citizenship { get; set; }
        public int EmployeeID { get; set; }
        public string PIN { get; set; }
        public byte[] Picture { get; set; }
        public string ApplicantTrackingIdentifier { get; set; }
    
        public virtual Miscellaneous_Countries Miscellaneous_Countries { get; set; }
        public virtual Miscellaneous_CountrySubdivisions Miscellaneous_CountrySubdivisions { get; set; }
        public virtual Miscellaneous_CountrySubdivisions Miscellaneous_CountrySubdivisions1 { get; set; }
        public virtual Lookups_EyeColors Miscellaneous_EyeColors { get; set; }
        public virtual Lookups_HairColors Miscellaneous_HairColors { get; set; }
        public virtual Lookups_NamePrefixes Miscellaneous_NamePrefixes { get; set; }
        public virtual Lookups_NameSuffixes Miscellaneous_NameSuffixes { get; set; }
        public virtual Lookups_Races Miscellaneous_Races { get; set; }
        public virtual Lookups_Sexes Miscellaneous_Sexes { get; set; }
        public virtual ICollection<Lookups_Person_FelonyAnswers> Person_FelonyAnswers { get; set; }
        public virtual ICollection<Lookups_Person_Aliases> Person_Aliases { get; set; }
        public virtual ICollection<Lookups_Security_Users> Security_Users { get; set; }
        public virtual Lookups_Person_Persons Person_Persons { get; set; }
        public virtual ICollection<Lookups_Person_Trainers> Person_Trainers { get; set; }
    }
    
}
