//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Facility_Staff
    {
        public Lookups_Facility_Staff()
        {
            this.Division_Divisions = new HashSet<Lookups_Division_Divisions>();
            this.Company_Companies = new HashSet<Lookups_Company_Companies>();
            this.Company_Companies1 = new HashSet<Lookups_Company_Companies>();
            this.Access_PersonDivisionCategoryXref = new HashSet<Lookups_Access_PersonDivisionCategoryXref>();
            this.Access_PersonDivisionCategoryXref1 = new HashSet<Lookups_Access_PersonDivisionCategoryXref>();
            this.Facility_StaffDepartmentXref = new HashSet<Lookups_Facility_StaffDepartmentXref>();
            this.Person_BadgeAccessPeriods = new HashSet<Lookups_Person_BadgeAccessPeriods>();
            this.Person_BadgeAccessPeriods1 = new HashSet<Lookups_Person_BadgeAccessPeriods>();
            this.Division_DivisionNotes = new HashSet<Lookups_Division_DivisionNotes>();
            this.Tasks = new HashSet<Lookups_Task>();
            this.Audit_AuditSpecifications = new HashSet<Lookups_Audit_AuditSpecifications>();
        }
    
        public int StaffID { get; set; }
        public int UserID { get; set; }
        public int C_DataChanges_RowID { get; set; }
        public string C_Legacy_UserIdentifiers { get; set; }
    
        public virtual Lookups_Security_Users Security_Users { get; set; }
        public virtual ICollection<Lookups_Division_Divisions> Division_Divisions { get; set; }
        public virtual ICollection<Lookups_Company_Companies> Company_Companies { get; set; }
        public virtual ICollection<Lookups_Company_Companies> Company_Companies1 { get; set; }
        public virtual ICollection<Lookups_Access_PersonDivisionCategoryXref> Access_PersonDivisionCategoryXref { get; set; }
        public virtual ICollection<Lookups_Access_PersonDivisionCategoryXref> Access_PersonDivisionCategoryXref1 { get; set; }
        public virtual ICollection<Lookups_Facility_StaffDepartmentXref> Facility_StaffDepartmentXref { get; set; }
        public virtual ICollection<Lookups_Person_BadgeAccessPeriods> Person_BadgeAccessPeriods { get; set; }
        public virtual ICollection<Lookups_Person_BadgeAccessPeriods> Person_BadgeAccessPeriods1 { get; set; }
        public virtual ICollection<Lookups_Division_DivisionNotes> Division_DivisionNotes { get; set; }
        public virtual ICollection<Lookups_Task> Tasks { get; set; }
        public virtual ICollection<Lookups_Audit_AuditSpecifications> Audit_AuditSpecifications { get; set; }
    }
    
}
