//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Person_FelonyAnswers
    {
        public int PersonID { get; set; }
        public int FelonyQuestionID { get; set; }
        public Nullable<bool> Answer { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual Lookups_Person_FelonyQuestions Person_FelonyQuestions { get; set; }
        public virtual Lookups_Person_PersonBiographics Person_PersonBiographics { get; set; }
    }
    
}
