//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Common_Requirement_LegalStatusTypes
    {
        public Lookups_Common_Requirement_LegalStatusTypes()
        {
            this.Common_Requirement_DocumentTypes = new HashSet<Lookups_Common_Requirement_DocumentTypes>();
        }
    
        public string LegalStatusCode { get; set; }
        public string LegalStatusDescription { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual ICollection<Lookups_Common_Requirement_DocumentTypes> Common_Requirement_DocumentTypes { get; set; }
    }
    
}
