//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Person_PersonDivisionJobRoleXref
    {
        public int PersonDivisionXrefID { get; set; }
        public short JobRoleID { get; set; }
        public short LocationID { get; set; }
        public System.DateTime WhenBegins { get; set; }
        public System.DateTime WhenEnds { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
        public string C_Legacy_TableName { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual Person_PersonDivisionXref Person_PersonDivisionXref { get; set; }
        public virtual Lookups_Person_JobRoles Person_JobRoles { get; set; }
    }
    
}
