//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Facility_Departments
    {
        public Lookups_Facility_Departments()
        {
            this.Facility_StaffDepartmentXref = new HashSet<Lookups_Facility_StaffDepartmentXref>();
            this.Common_Requirement_Requirements = new HashSet<Lookups_Common_Requirement_Requirements>();
        }
    
        public short DepartmentID { get; set; }
        public string FacilityCode { get; set; }
        public string DepartmentName { get; set; }
        public string DepartmentAbbreviation { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public short C_DataChanges_RowID { get; set; }
    
        public virtual ICollection<Lookups_Facility_StaffDepartmentXref> Facility_StaffDepartmentXref { get; set; }
        public virtual ICollection<Lookups_Common_Requirement_Requirements> Common_Requirement_Requirements { get; set; }
    }
    
}
