//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Facility_StaffDepartmentXref
    {
        public int StaffID { get; set; }
        public short DepartmentID { get; set; }
        public short DepartmentOrder { get; set; }
        public bool CanAssignWorkQueue { get; set; }
        public bool CanFulfillWorkQueue { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual Lookups_Facility_Departments Facility_Departments { get; set; }
        public virtual Lookups_Facility_Staff Facility_Staff { get; set; }
    }
    
}
