//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Lookups_Person_Badges
    {
        public Lookups_Person_Badges()
        {
            this.Common_Entities = new HashSet<Lookups_Common_Entities>();
            this.Person_BadgeIconPeriods = new HashSet<Lookups_Person_BadgeIconPeriods>();
            this.Person_BadgeAccessPeriods = new HashSet<Lookups_Person_BadgeAccessPeriods>();
        }
    
        public int BadgeID { get; set; }
        public int PersonDivisionXrefID { get; set; }
        public Nullable<long> BadgeID_IWS { get; set; }
        public string BadgeNumber { get; set; }
        public string ProxNumber { get; set; }
        public string BadgeIssuanceReasonCode { get; set; }
        public Nullable<short> BadgeColorID { get; set; }
        public System.DateTime WhenBecomesActive { get; set; }
        public System.DateTime WhenExpires { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
        public string C_Legacy_TableName { get; set; }
        public Nullable<System.DateTime> C_Legacy_BadgeReturnDate_ONT { get; set; }
        public Nullable<byte> C_Legacy_PersonType_ONT { get; set; }
        public int C_DataChanges_RowID { get; set; }
        public bool DriveThroughGates { get; set; }
        public bool DriverLEO { get; set; }
        public Nullable<int> CardNumber { get; set; }
    
        public virtual ICollection<Lookups_Common_Entities> Common_Entities { get; set; }
        public virtual Lookups_Facility_BadgeColors Facility_BadgeColors { get; set; }
        public virtual ICollection<Lookups_Person_BadgeIconPeriods> Person_BadgeIconPeriods { get; set; }
        public virtual Lookups_Person_BadgeIssuanceReasons Person_BadgeIssuanceReasons { get; set; }
        public virtual Person_PersonDivisionXref Person_PersonDivisionXref { get; set; }
        public virtual ICollection<Lookups_Person_BadgeAccessPeriods> Person_BadgeAccessPeriods { get; set; }
    }
    
}
