//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Miscellaneous_CountrySubdivisions
    {
        public Miscellaneous_CountrySubdivisions()
        {
            this.Person_PersonBiographics = new HashSet<Lookups_Person_PersonBiographics>();
            this.Person_PersonBiographics1 = new HashSet<Lookups_Person_PersonBiographics>();
            this.Division_Contacts = new HashSet<Lookups_Division_Contacts>();
            this.LEO_PoliceDepartments = new HashSet<LEO_PoliceDepartments>();
            this.Common_Requirement_Documents = new HashSet<Lookups_Common_Requirement_Documents>();
        }
    
        public string CountryCode { get; set; }
        public string CountrySubdivisionCode { get; set; }
        public string CountrySubdivisionName { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public int C_DataChanges_RowID { get; set; }
        public string NCICCountrySubdivisionCode { get; set; }
    
        public virtual Miscellaneous_Countries Miscellaneous_Countries { get; set; }
        public virtual ICollection<Lookups_Person_PersonBiographics> Person_PersonBiographics { get; set; }
        public virtual ICollection<Lookups_Person_PersonBiographics> Person_PersonBiographics1 { get; set; }
        public virtual ICollection<Lookups_Division_Contacts> Division_Contacts { get; set; }
        public virtual ICollection<LEO_PoliceDepartments> LEO_PoliceDepartments { get; set; }
        public virtual ICollection<Lookups_Common_Requirement_Documents> Common_Requirement_Documents { get; set; }
    }
    
}
