//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Person_STAEmployeeStatuses
    {
        public Person_STAEmployeeStatuses()
        {
            this.Person_PersonDivisionXref = new HashSet<Person_PersonDivisionXref>();
        }
    
        public short STAEmployeeStatusID { get; set; }
        public string STAEmployeeStatusTitle { get; set; }
        public bool IsActive { get; set; }
        public short SortOrder { get; set; }
        public int C_DataChanges_RowID { get; set; }
    
        public virtual ICollection<Person_PersonDivisionXref> Person_PersonDivisionXref { get; set; }
    }
    
}
