//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Person_PersonDivisionXref
    {
        public Person_PersonDivisionXref()
        {
            this.Icon_PersonDivisionIconXref = new HashSet<Lookups_Icon_PersonDivisionIconXref>();
            this.Common_Entities = new HashSet<Lookups_Common_Entities>();
            this.Person_PersonDivisionJobRoleXref = new HashSet<Lookups_Person_PersonDivisionJobRoleXref>();
            this.Person_Badges = new HashSet<Lookups_Person_Badges>();
            this.BackgroundCheck_PersonDivisionChecks = new HashSet<Lookups_BackgroundCheck_PersonDivisionChecks>();
            this.Access_PersonDivisionCategoryXref = new HashSet<Lookups_Access_PersonDivisionCategoryXref>();
        }
    
        public int PersonDivisionXrefID { get; set; }
        public int PersonID { get; set; }
        public int DivisionID { get; set; }
        public System.DateTime WhenAccepted { get; set; }
        public System.DateTime WhenBegins { get; set; }
        public System.DateTime WhenEnds { get; set; }
        public string C_Legacy_DatabaseName { get; set; }
        public string C_Legacy_TableName { get; set; }
        public int C_DataChanges_RowID { get; set; }
        public Nullable<short> STAEmployeeStatusID { get; set; }
        public string FederalIDLEONumber { get; set; }
        public Nullable<bool> IsSTACheckRequired { get; set; }
        public string ApplicantType { get; set; }
        public Nullable<bool> SubmittedStateDoJRequest { get; set; }
    
        public virtual ICollection<Lookups_Icon_PersonDivisionIconXref> Icon_PersonDivisionIconXref { get; set; }
        public virtual ICollection<Lookups_Common_Entities> Common_Entities { get; set; }
        public virtual ICollection<Lookups_Person_PersonDivisionJobRoleXref> Person_PersonDivisionJobRoleXref { get; set; }
        public virtual ICollection<Lookups_Person_Badges> Person_Badges { get; set; }
        public virtual Lookups_Division_Divisions Division_Divisions { get; set; }
        public virtual Lookups_Person_Persons Person_Persons { get; set; }
        public virtual ICollection<Lookups_BackgroundCheck_PersonDivisionChecks> BackgroundCheck_PersonDivisionChecks { get; set; }
        public virtual ICollection<Lookups_Access_PersonDivisionCategoryXref> Access_PersonDivisionCategoryXref { get; set; }
        public virtual Person_STAEmployeeStatuses Person_STAEmployeeStatuses { get; set; }
    }
    
}
