//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace AirportIQ.Model.EF.LookUps
{
    public partial class Security_Groups
    {
        public byte GroupID { get; set; }
        public byte ApplicationID { get; set; }
        public string GroupName { get; set; }
        public string GroupDescription { get; set; }
        public byte[] ActiveDirectoryGroupSID { get; set; }
        public byte C_DataChanges_RowID { get; set; }
    }
    
}
